#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# mupdf-tools
export PATH="$HOME/app/mupdf/bin:$PATH"

# set prompt
source $HOME/.bash_prompt

# system
alias install='sudo pacman -S'
alias search='sudo pacman -Ss'
alias update='sudo pacman -S archlinux-keyring && sudo pacman -Syu'
alias remove='sudo pacman -Rcn'
alias poweroff='sudo shutdown -h now'
alias reboot='sudo reboot'

# emacs
alias em='emacs'
alias emc="emacsclient -a '' -t"
# only load basic text package to startup quickly.
alias emq='emacs -Q --eval "(setq startup-now t)" -l "~/.emacs.d/init.el"'